version: "3.8"
services:
  minio:
    profiles: ["bucket"]
    image: minio/minio
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-AKIAIOSFODNN7EXAMPLE}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY}
      - MINIO_BUCKET=${BUCKET_NAME:-briefkasten-dev}
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
  mc:
    image: minio/mc:latest
    profiles: ["bucket"]
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-AKIAIOSFODNN7EXAMPLE}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY}
      - MINIO_BUCKET=${BUCKET_NAME:-briefkasten-dev}
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set local http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb local/$${MINIO_BUCKET};
      /usr/bin/mc anonymous set download local/$${MINIO_BUCKET};
      "
  database:
    profiles: ["database"]
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-briefkasten}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
