version: "3.8"
services:
  sveltekasten-web:
    build: 
      context: .
      tags: 
        - web:latest
      target: web
    restart: unless-stopped
    networks: 
      - sveltekasten_network
    ports:
      - "3000:3000"
    env_file: ./apps/web/.env
  sveltekasten-backend:
    build: 
      context: .
      tags: 
        - backend:latest
      target: backend
    networks: 
      - sveltekasten_network
    restart: unless-stopped
    env_file: apps/backend/.env

networks:
  sveltekasten_network:
