version: "3.8"
services:
  database:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?err}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?err}
      - POSTGRES_DB=${POSTGRES_DB:?err}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database:/var/lib/postgresql/data
  sveltekasten:
    depends_on:
      database:
        condition: service_healthy
    build: .
    volumes:
      - "./src:/app/src"
    command: npm run dev
    environment:
    - PORT=${PORT:-3000}
    - AUTH_SECRET=${AUTH_SECRET:?err}
    env_file: .env
    ports:
    - ${PORT:-3000}:${PORT:-3000}
    environment:
      - NODE_ENV=development
      - PORT=5000
      - HOST=0.0.0.0
