version: "3.8"
services:
  sveltekasten-web:
    build: 
      context: .
      dockerfile: ./apps/web/Dockerfile
      args: 
        PACKAGE_PATH: apps/web/
    restart: unless-stopped
    networks: 
      - sveltekasten_network
    ports:
      - "3000:3000"
    env_file: ./apps/web/.env
  sveltekasten-backend:
    build: 
      context: .
      dockerfile: ./apps/backend/Dockerfile
      args: 
        PACKAGE_PATH: apps/web/
    networks: 
      - sveltekasten_network
    restart: unless-stopped
    env_file: apps/backend/.env

networks:
  sveltekasten_network:
