version: "3.8"
services:
  sveltekasten:
    build: .
    volumes:
      - "./src:/app/src"
    command: npm run dev
    ports:
      - "5000:5000"
      - "3000:3000"
    env_file: .env
    restart: on-failure
    environment:
      - NODE_ENV=development
      - PORT=5000
      - HOST=0.0.0.0
