name: Playwright Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"
          cache-dependency-path: |
            pnpm-lock.yaml
            apps/web/prisma/schema.prisma
      - name: Install dependencies
        run: pnpm install
      - name: Generate prisma client
        run: pnpm --filter sveltekasten-web db:generate
      - name: Run Playwright tests
        run: pnpm --filter sveltekasten-web test:e2e
        env:
          AUTH_SECRET: ${{ vars.AUTH_SECRET }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
